### ISSUE TITLE
[BUG] : The spread syntax (**) gives error

### ISSUE THREAD

**Issue by AshishMahendra** [Jaseci-Labs/jaclang#261]
**Describe the bug**
The spread syntax (**) for dictionaries is giving an Error. E.g.: The attempt to spread the contents of dictionary a into dictionary y in the below code gives a syntax error.
**To Reproduce**

**example code:**
with entry{
    x={"a":"apple", "b":"ball", "c":"cat"};
    y={**a, "d":"dog", "e":"elephant"};
}
**error:**
ERROR - test.jac, line 3, col 16: Syntax Error: Unexpected token Token('COLON', ':') at line 3, column 16.
Expected one of: 
        * COMMA
        * RBRACE

test.jac, line 3, col 16: Syntax Error: Unexpected token Token('COLON', ':') at line 3, column 16.
Expected one of: 
        * COMMA
        * RBRACE

ERROR - test.jac, line 3, col 16: Syntax Error: Unexpected token Token('COLON', ':') at line 3, column 16.
Expected one of: 
        * COMMA
        * RBRACE
        
**Jaclang/Python Version**
Python version and Jac version, or installed from source.
Python - 3.11.6
jaclang - 0.4.7

**Comment by marsninja** [comment]
Hi @AshishMahendra , Jaclang 0.4.7 is ooooooollllllllddddd :-P. This issue was fixed a long time ago. I did add yoru example code to an existing test and it pass as per below. 

Added this syntax
![image](https://github.com/Jaseci-Labs/jaclang/assets/8206008/9361c6fd-53a0-44c4-8e22-8de6ecdf48bc)
to an existing test and I currently get this output
![image](https://github.com/Jaseci-Labs/jaclang/assets/8206008/9f6c5495-fd3b-476d-8e7e-38426072a3da)
